In [ ]:
A = "Anwarul"
B = " Azim"
print(f"Hello {A} {B}, welcome to python programming")

Hello Anwarul  Azim, welcome to python programming

In [ ]:
Name = 'Anwarul Azim Sayem'
print(Name[10])
print(Name[8 : 12])
Upper_Case = Name.upper()
print(Upper_Case)
Replace_Word = Name.replace('Azim', 'Islam')
print(Replace_Word)

i
Azim
ANWARUL AZIM SAYEM
Anwarul Islam Sayem

In [ ]:
Fruits = ['Apple', 'Banana', 'Cherry']
Second_fruits = Fruits[1]
print(Second_fruits)
Fruits.append('Orange')
print(Fruits)
Fruits.insert(2, 'Mango')
print(Fruits)
Fruits.insert(len(Fruits), 'Berry')
print(Fruits)
Fruits.insert(-1, 'Pineapple')
print(Fruits)
del Fruits[1]
print(Fruits)
Fruits.remove('Mango')
print(Fruits)
Fruits.pop()
print(Fruits)
Count = Fruits.count(2)
print(Count)
New_fruits = Fruits.copy()
print(New_fruits)
Fruits.clear()
print(Fruits)

Banana
['Apple', 'Banana', 'Cherry', 'Orange']
['Apple', 'Banana', 'Mango', 'Cherry', 'Orange']
['Apple', 'Banana', 'Mango', 'Cherry', 'Orange', 'Berry']
['Apple', 'Banana', 'Mango', 'Cherry', 'Orange', 'Pineapple', 'Berry']
['Apple', 'Mango', 'Cherry', 'Orange', 'Pineapple', 'Berry']
['Apple', 'Cherry', 'Orange', 'Pineapple', 'Berry']
['Apple', 'Cherry', 'Orange', 'Pineapple']
0
['Apple', 'Cherry', 'Orange', 'Pineapple']
[]

Dictionary

In [ ]:
Sayem = {

       'Name'   : 'Anwarul Azim Sayem',
       'Age'    : 23,
       'Grades' : {'Database' : 3.5,  'Algorithm' : 3.75,  'Data_Structure' : 3.5} # Nested Dictionary
}

In [ ]:
print(Sayem['Grades']['Algorithm'])

3.75

In [ ]:
Fruits = ['Apple', 'Banana', 'Cherry']
Last_fruits = Fruits[-1]         # (To find out Last index)
print(Last_fruits)                 #  => Cherry
Fruits.append('Orange')            # (To insert at the last)
print(Fruits)                      #  => ['Apple', 'Banana', 'Cherry', 'Orange']
Fruits.insert(2, 'Mango')          # (To insert at the specific position)
print(Fruits)                      #  => ['Apple', 'Banana', 'Mango', 'Cherry', 'Orange']
Fruits.insert(len(Fruits), 'Berry')# (To insert at the last)
print(Fruits)                      #  => ['Apple', 'Banana', 'Mango', 'Cherry', 'Orange', 'Berry']
Fruits.insert(-1, 'Pineapple')     # (To insert at the Second-to-last position)
print(Fruits)                      #  => ['Apple', 'Banana', 'Mango', 'Cherry', 'Orange', 'Pineapple', 'Berry']
del Fruits[1]                      # (To remove specific index from the list)
print(Fruits)                      #  => ['Apple', 'Mango', 'Cherry', 'Orange', 'Pineapple', 'Berry']
Fruits.remove('Mango')             # (To remove specific item from the list)
print(Fruits)                      #  => ['Apple', 'Cherry', 'Orange', 'Pineapple', 'Berry']
Fruits.pop()                       # (To remove from the last position)
print(Fruits)                      #  => ['Apple', 'Cherry', 'Orange', 'Pineapple']
Count = Fruits.count('Coconut')      # (To count how many coconuts have into the list)
print(Count)                       #  => 0
New_fruits = Fruits.copy()         # (To copy the list)
print(New_fruits)                  #  => ['Apple', 'Cherry', 'Orange', 'Pineapple']
Fruits.clear()
print(Fruits)                      #  => [] (To Clear the list)
                                   # print(Fruits[start : End+1])     =>List Slicing

Cherry
['Apple', 'Banana', 'Cherry', 'Orange']
['Apple', 'Banana', 'Mango', 'Cherry', 'Orange']
['Apple', 'Banana', 'Mango', 'Cherry', 'Orange', 'Berry']
['Apple', 'Banana', 'Mango', 'Cherry', 'Orange', 'Pineapple', 'Berry']
['Apple', 'Mango', 'Cherry', 'Orange', 'Pineapple', 'Berry']
['Apple', 'Cherry', 'Orange', 'Pineapple', 'Berry']
['Apple', 'Cherry', 'Orange', 'Pineapple']
0
['Apple', 'Cherry', 'Orange', 'Pineapple']
[]

In [ ]:
Num = [0,3,9,1,4,6,0,5,4,6,9,1]
ans = 0
for i in range(len(Num)):
  count = 0
  for j in range(i+1, len(Num)):
    if Num[i] == Num[j]:
      count += 1
  ans += count
print(ans)          # => 5

5

In [ ]:
Num = [9,0,3,1,4,6,0,5,4,6,9,1,8]
result = []
for i in range(len(Num)):
  count = 0
  for j in range(len(Num)):
    if Num[i] > Num[j]:
      count += 1
  if count not in result:
   result.append(count)
print(result) # =>  if count not in result:

[11, 0, 4, 2, 5, 8, 7, 10]

In [ ]:
Num = [9,0,3,1,4,6,0,5,4,6,9,1,8] #[0,0,1,1,3,4,4,5,6,6,8,9,9]
dic = {}                            # [0: 0]
result = []                         # [1: 2]
sort_num = sorted(Num)              # [3: 4]
for i in range(len(sort_num)):      # [4: 5]
  if sort_num[i] not in dic: #------> [5: 7]  [number: Index]
    dic[sort_num[i]] = i            # [6: 8]
for k in Num:                       # [8: 10]
  if dic[k] not in result:          # [9: 11]
   result.append(dic[k])
print(dic) # =>{0: 0, 1: 2, 3: 4, 4: 5, 5: 7, 6: 8, 8: 10, 9: 11}
print(result)  # =>[11, 0, 4, 2, 5, 8, 7, 10]

{0: 0, 1: 2, 3: 4, 4: 5, 5: 7, 6: 8, 8: 10, 9: 11}
[11, 0, 4, 2, 5, 8, 7, 10]

In [ ]:
Num = [9,0,3,1,4,6,5,8,2,7] # Find the pair from the list which addition = terget
result = []
terget = 10
for i in Num:
  for j in Num:
    if Num[i] != Num[j]:
     if Num[i] and Num[j] not in result:
      if Num[i] + Num[j] == terget:
       result.append(Num[i])
       print(Num[i], Num[j])
print(result)

7 3
9 1
4 6
2 8
[7, 9, 4, 2]

In [ ]:
Num = [9, 0, 3, 1, 4, 6, 5, 8, 2, 7]
target = 10
result = []
dic = {}  # Dictionary to store numbers

for i in Num:
    complement = target - i
    if complement in dic:  # Check if complement exists in the dictionary
        result.append((i, complement))
        print(i, complement)
    dic[i] = True  # Add the current number to the dictionary

# Print result pairs
print(result)

1 9
6 4
2 8
7 3
[(1, 9), (6, 4), (2, 8), (7, 3)]

In [6]:
# 03
even = 0
odd = 0

print("Enter numbers one by one. Enter 0 to stop.")

while True:
    num = int(input("Enter a number: "))
    if num == 0:
        break
    elif num % 2 == 0:
        even += 1
    else:
        odd += 1

print(f"Total even numbers: {even}")
print(f"Total odd numbers: {odd}")

Enter numbers one by one. Enter 0 to stop.
Enter a number: 3
Enter a number: 6
Enter a number: 1
Enter a number: 2
Enter a number: 3
Enter a number: 4
Enter a number: 5
Enter a number: 9
Enter a number: 8
Enter a number: 7
Enter a number: 6
Enter a number: 0
Total even numbers: 5
Total odd numbers: 6

In [11]:
# 04
Num = int(input("Enter any positive integer number: "))
fact = 1
for i in range(1, Num + 1):
  fact *= i

print(fact)

Enter any positive integer number: 6
720

In [12]:
# 05
num = int(input("Enter a number to generate its multiplication table: "))

for i in range(1, 13):
    print(f"{num} x {i} = {num * i}")

Enter a number to generate its multiplication table: 7
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70
7 x 11 = 77
7 x 12 = 84

In [14]:
# 06
Large = None

while True:
    Num = int(input("Enter any number (enter -1 to stop): "))
    if Num == -1:
        break
    if Large is None or Num > Large:
        Large = num

if Large is not None:
    print(f"The largest number entered is: {Large}")
else:
    print("No valid number was entered.")

Enter any number (enter -1 to stop): 5
Enter any number (enter -1 to stop): 7
Enter any number (enter -1 to stop): 6
Enter any number (enter -1 to stop): 3
Enter any number (enter -1 to stop): 8
Enter any number (enter -1 to stop): 0
Enter any number (enter -1 to stop): -1
The largest number entered is: 8

In [18]:
# 07
num = int(input("Enter a number to check if it is prime: "))

if num <= 1:
    print("Not Prime")
else:
    is_prime = True
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        print("Prime")
    else:
        print("Not Prime")

Enter a number to check if it is prime: 17
Prime

In [23]:
Marks = int(input("Enter your marks: "))
if Marks >= 90 and Marks <= 100:
  print('A')
elif Marks >=80 and Marks <90:
  print('B')
elif Marks >=70 and Marks <80:
  print('C')
elif Marks >=60 and Marks <70:
  print('D')
elif Marks >=0 and Marks <60:
  print('f')
else:
  print('Invelid Marks')

Enter your marks: 88
B

In [26]:
String = input('Enter any string: ')
count = 0
for i in String:
  if i=='a' or i=='A' or i=='e' or i=='E' or i=='i' or i=='I' or i=='o' or i=='O' or i=='u' or i=='U':
    count += 1
print(f'provided string have {count} vowels')

Enter any string: Anwarul Azim Sayem
provided string have 7 vowels

In [29]:
balance = 0
while True:
    print("1. Check Balance")
    print("2. Deposit Money")
    print("3. Withdraw Money")
    print("4. Exit")

    choice = input("Please choose an option : ")
    if choice == "1":
        print(f"Your current balance is: bdt{balance}")

    elif choice == "2":
        try:
            deposit = float(input("Enter amount to deposit: bdt"))
            if deposit <= 0:
                print("Deposit amount must be positive!")
            else:
                balance += deposit
                print(f"Deposited bdt{deposit}. Your new balance is: bdt{balance}")
        except ValueError:
            print("Invalid input! Please enter a valid number.")

    elif choice == "3":
        try:
            withdrawal = float(input("Enter amount to withdraw: bdt"))
            if withdrawal <= 0:
                print("Withdrawal amount must be positive!")
            elif withdrawal > balance:
                print("Insufficient balance! Withdrawal amount exceeds available balance.")
            else:
                balance -= withdrawal
                print(f"Withdrew bdt{withdrawal}. Your new balance is: bdt{balance}")
        except ValueError:
            print("Invalid input! Please enter a valid number.")

    elif choice == "4":
        print("Exiting the banking system")
        break

    else:
        print("Invalid choice! Please select a valid option.")

1. Check Balance
2. Deposit Money
3. Withdraw Money
4. Exit
Please choose an option : 2
Enter amount to deposit: bdt17000
Deposited bdt17000.0. Your new balance is: bdt17000.0
1. Check Balance
2. Deposit Money
3. Withdraw Money
4. Exit
Please choose an option : 3
Enter amount to withdraw: bdt5000
Withdrew bdt5000.0. Your new balance is: bdt12000.0
1. Check Balance
2. Deposit Money
3. Withdraw Money
4. Exit
Please choose an option : 1
Your current balance is: bdt12000.0
1. Check Balance
2. Deposit Money
3. Withdraw Money
4. Exit
Please choose an option : 4
Exiting the banking system